[package]
name = "solana-alt-bn128-bls-test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-alt-bn128-bls = { path = "../" }
pinocchio = "0.6.0"

[dev-dependencies]
mollusk-svm = "0.0.11"
solana-sdk = "2.1.0"